### ISSUE TITLE
Qdrant Demo

### ISSUE THREAD

**Issue by makl9797** [makl9797/forschungsprojekt-ccc#2]
### Beschreibung 
Als Start soll eine kleine Demo gebaut werden die mit der Hilfe eines Embedding Models den Text von verschiedenen Dateien (.txt oder .pdf) in Vektoren umwandelt und diese in einer [Qdrant](https://qdrant.tech/) Vektordatenbank speichert. An diese Datenbank sollen Fragen oder Text in Form von einer Suchanfrage geschickt werden. Die Datenbank antwortet mit einer festgelegten Anzahl an Ergebnissen, die zu dem Text passen oder die die Frage beantworten könnten.

**Comment by jehe8622** [comment]
branch: prototype-py
Demo hochgeladen

**Comment by makl9797** [comment]
Ich schließe das Issue, da die nächsten Schritte in Issue #4 und #5 aufgeteilt wurden und somit an dieser Stelle alles erledigt ist.
